### ISSUE TITLE
[Marketing] Format and upload a case study to Mautic.org

### ISSUE THREAD

**Issue by RCheesley** [mautic/hacktoberfest-no-code#10]
We have a great [case study](https://www.mautic.org/case-studies) for mautic.org which needs formatting and uploading.

Please log in at https://www.mautic.org with your forum account (or create a new one) and let us know your username so we can grant you editor rights.

Check the Case studies page for the layout you need to use: [https://www.mautic.org/case-studies](https://www.mautic.org/case-studies) - we use Drupal and the Layout Builder tab to build out these pages.  The quickest route is to view source for the section, copy it, and paste it into your new article.

Select an appropriate free image (you can use freepik, unsplash, pixabay etc) to accompany and crop it to the correct size.

Content:
### Introduction
In the wake of the COVID-19 pandemic, many businesses faced unprecedented challenges. Paellas Franco, a catering service specializing in delivering authentic Spanish paellas and related services in Peru, was no exception. Despite a rich history and a loyal customer base, the post-pandemic period saw a significant slowdown in business. Seeking innovative solutions, Paellas Franco partnered with Seven Cats Studio to revitalize their marketing strategy using Mautic, an open-source marketing automation tool. This case study explores how this collaboration transformed Paellas Franco's customer engagement and business performance.
### Background
**Client:** Paellas Franco ([paellasfranco.com](http://paellasfranco.com/))
**Agency:** Seven Cats Studio ([7catstudio.com](http://7catstudio.com/))
**Industry:** Catering Services
**Location:** Peru
Paellas Franco offers catering services for events, providing large paellas, barmen, chefs, servers, and all necessary dining equipment. The business operates exclusively on a delivery basis, serving events ranging from small gatherings to large celebrations for up to 300 people.
### The Challenge
Before implementing Mautic, Paellas Franco struggled with declining sales and customer engagement. Monthly revenues had dropped to approximately 15,000 soles (around $4,000). Despite having a database of 1,500 former clients, reconnecting with them and attracting new customers proved challenging.
### The Solution
Seven Cats Studio proposed a strategic use of Mautic to automate and personalize communication with Paellas Franco's client base. The strategy focused on leveraging WhatsApp for direct messaging campaigns, using Zender, a multi-form tool developed by Seven Cats Studio, to send personalized, untrackable WhatsApp messages.
### Campaign Strategy
1. **Target Audience:**
   - A database of 1,500 former clients.
   - Focus on re-engaging lapsed customers and attracting new clients through referrals.
2. **Message Content:**
   - Non-sales oriented messages, including greetings for events such as Mother's Day and Father's Day, and simple well-wishing messages.
   - Objective: Increase engagement and maintain top-of-mind awareness without direct sales pressure.
3. **Frequency:**
   - Two personalized WhatsApp messages per month.
4. **Engagement Rules:**
   - Monitoring and analyzing responses on both WhatsApp and email.
   - Encouraging positive interaction without pushing for immediate sales.
### Results
The implementation of Mautic and the strategic use of personalized WhatsApp messages yielded remarkable results for Paellas Franco:
1. **Revenue Growth:**
   - Monthly revenues increased from 15,000 soles ($4,000) to over $9,000 by May 2024.
   - By June 2024, sales had grown to 2.5 times the pre-campaign levels.
2. **Customer Re-engagement:**
   - Successfully re-engaged 30 former clients who had not purchased in the last five years.
   - Gained 9-10 new customer referrals through the campaign.
3. **Enhanced Interaction:**
   - Received approximately 4,000-5,000 responses to the WhatsApp messages.
   - Increased website and social media activity, leading to additional small-scale business opportunities.
### Conclusion
The case of Paellas Franco demonstrates the power of Mautic in revitalizing customer engagement and driving business growth. By focusing on personalized, non-sales messaging and leveraging the capabilities of Mautic for automation, Seven Cats Studio was able to significantly enhance Paellas Franco's customer relationships and revenue.
This case study underscores the potential of strategic marketing automation in transforming business performance, especially for services-based businesses navigating post-pandemic recovery.
For more information about Seven Cats Studio and Paellas Franco, visit their websites at [[7catstudio.com](http://7catstudio.com/)](http://7catstudio.com/) and [[paellasfranco.com](http://paellasfranco.com/)](http://paellasfranco.com/).

**Comment by ASHMITA489** [comment]
I'm willing to solve this issue. Can you please assign it to me?

**Comment by RCheesley** [comment]
Absolutely @ASHMITA489 - please follow the steps above and let us know if you need any help!

**Comment by ASHMITA489** [comment]
Sure. Thanks!

**Comment by ASHMITA489** [comment]
Sure
My login username is "Ashmita".
I am facing some difficulty in building the content page, but I'll get it
done soon.

**Comment by RCheesley** [comment]
Super, I've ranked your account up to editor so you should be able to create pages and use the layout builder, but give me a shout if you get stuck as the permissions are a bit tricky on the website!

**Comment by RCheesley** [comment]
Thanks so much for all your hard work on this @ASHMITA489 - please do make an edit to the 2024 file to add your contribution so it counts for Hacktoberfest! Shout if you need any help with that!
