### ISSUE TITLE
[Content] Review and update the content on the communication channels page

### ISSUE THREAD

**Issue by RCheesley** [mautic/hacktoberfest-no-code#25]
This issue has a corresponding Jira ticket here: https://mautic.atlassian.net/browse/WR-173. Ping us in #hacktoberfest if you need inviting to Jira. The content is written below.

You will find the wireframes for the new website at https://www.figma.com/design/OIqb9D6IT3mOP2HjqlZ230/Mautic.org-website-wireframe?node-id=71-267&t=wmMT8GYs1z5xCZuH-1 which shows the kinds of blocks (far right) and layouts we have available. There is one specifically for community, so we need to write the content and decide if this layout will work for what we want to see on the page.

This page is intended to explain to people how they can engage with the Mautic project and community. It will be a sub-page of the Community page (see #6) so you should align closely with the person working on that task so that there's some continuity between the two.

If you'd like to make a mockup on Figma / Canva / Whatever to show the web team how you'd like this page to look (e.g. if you want to use images, layouts etc), please do (and share it with us in the issue comments).

Copied below from the Jira issue:

This issue relates to updating the content for Communication channels, which you can find at https://www.mautic.org/community/get-involved/communication-channels. If there are any comments from the team they will be found below.

The link for writing the updated content can be found at https://docs.google.com/document/d/1sDNStEJ1kmuop0Emobs-gAjRI6Nioz65TVQoZYw1lk0/edit?usp=drivesdk.

Thanks for your help!

**Comment by adiati98** [comment]
Hi @RCheesley ,

I'm coming from the WriteTechHub community and interested in taking on this issue. 😊

**Comment by adiati98** [comment]
Hi @RCheesley,

Is this issue still available to grab?
I'm interested to work on it. 😊 

Just a quick question. What you'd like to do or have in the communication channels page?

**Comment by RCheesley** [comment]
I'd have a look at the current page: https://www.mautic.org/community and see whether you think this is helpful for actually getting people to the right channels. We have to consider we have different personas:

- **Marketers** who use Mautic (or could) for actually doing the marketing stuff
- **Developers** who build stuff with/for Mautic
- **Agencies/businesses** who use or need to offer a marketing automation solution for their clients / their business
- **User/implementor** who is responsible for using, maintaining and updating Mautic
- **Open Source enthusiasts** could also be a persona to consider(we didn’t really consider those as they are most likely focused on interest rather than need)

So these have different needs, and would need to have different communication options. Maybe look at other open source projects and see what their pages are like for comms channels, and see what we could do better!

**Comment by adiati98** [comment]
Hi @RCheesley,
I have some questions and throw some ideas in the GDoc. Please let me know what you and the team think about them. Thank you. 😊

**Comment by RCheesley** [comment]
Hi there, sorry for the delay we got a bit swamped with all the _awesomely amazing_ contributions!

I will have a look at this during the morning and get back to you with any thoughts!

**Comment by adiati98** [comment]
Hey @RCheesley,
I've written a draft for the page in the GDoc. Please let me know what you think when you have the chance. 🙂 
In the meantime, I still need some time to figure out how to use Canva or Figma for the wireframe. 😅

**Comment by RCheesley** [comment]
https://mauticstaging.com/join-the-conversation/ first draft here!
