### ISSUE TITLE
[Content] Format and upload case study to mautic.org (multi tenant)

### ISSUE THREAD

**Issue by RCheesley** [mautic/hacktoberfest-no-code#49]
We have a great [case study](https://www.mautic.org/case-studies) for mautic.org which needs formatting and uploading.

Please log in at https://www.mautic.org/ with your forum account (or create a new one) and let us know your username so we can grant you editor rights.

Check the Case studies page for the layout you need to use: https://www.mautic.org/case-studies - we use Drupal and the Layout Builder tab to build out these pages. The quickest route is to view source for the section, copy it, and paste it into your new article.

Check the proposed images and select one to use. Crop it to the correct size.

Case study content: https://community.mautic.org/processes/mautic-awards-2024/f/85/proposals/72

**Comment by RCheesley** [comment]
@ASHMITA489 here's one to start on! :)

**Comment by ASHMITA489** [comment]
Can you please assign it to me?
