### ISSUE TITLE
[Translations] Translate the user interface for kb.mautic.org to French

### ISSUE THREAD

**Issue by RCheesley** [mautic/hacktoberfest-no-code#63]
Our Knowledgebase is available in specific languages where the translations have been made - this issue is to translate the user interface into French, so that we will then be able to translate the content into French as well.

If you'd like to work on other languages/translate articles just let us know!

**Comment by RCheesley** [comment]
@laurielim here's the task!

**Comment by laurielim** [comment]
Thank you, I'll get started on this :)

**Comment by laurielim** [comment]
I've translated the UI to French.

**Comment by RCheesley** [comment]
Closing as completed per #73
