### ISSUE TITLE
[Content] Add new blog post

### ISSUE THREAD

**Issue by RCheesley** [mautic/hacktoberfest-no-code#64]
We have a blog post which needs adding to the mautic.org blog which will need experience with formatting as there's inline images which need to be aligned etc. The content is sensitive so I won't share the doc link here.

Please ping me if you'd like to be assigned to this task!

**Comment by markusVJH** [comment]
I can gives this a go

**Comment by RCheesley** [comment]
Awesome, thanks @markusVJH !

**Comment by markusVJH** [comment]
Hey, added the blog as a draft :)

**Comment by RCheesley** [comment]
Thanks @markusVJH this will be posted during the Mautic Conference Europe event - please do make the PR to https://github.com/mautic/hacktoberfest-no-code if you want it to count for Hacktoberfest!

**Comment by markusVJH** [comment]
Added the [PR](https://github.com/mautic/hacktoberfest-no-code/pull/85) :)
