### ISSUE TITLE
[Marketing/Design] Create visual to promote Dropsolid featured session as Gold Sponsor for Mautic Conference Europe 

### ISSUE THREAD

**Issue by RCheesley** [mautic/hacktoberfest-no-code#7]
This is documented in a Jira issue [here](https://mautic.atlassian.net/browse/MCON-1212), it's part of a [wider epic](https://mautic.atlassian.net/browse/MCON-1211) to promote this sponsor. See also #8 to write the content to accompany this task.

Instructions copied below:

> Dropsolid are a [Gold sponsor](https://opencollective.com/mautic/events/mautic-conference-europe-2024-17240ca6/contribute/gold-sponsorship-77750) for [Mautic Conference Europe 2024](https://mauticon.mautic.org/) - we need to make a visual which will promote one of their featured talks.
> 
> Please ask for access to Canva on Slack and one of the team will invite you. The company logos are on the Canva Brand Kit for Mautic Conference Europe.
> 
> Please design for:
> 
>
> - Facebook
> - Instagram (portrait rather than square - we use this for Mastodon and Threads also)
> - Twitter
> - LinkedIn
> - Instagram Story/Reel
> 
> Please check the [brand kit](https://www.canva.com/brand/kAGOTOcfQ5M) for the event in Canva and ensure you use those assets.
> 
> Please share the links to the Canva designs so we can review/approve, make a sub-folder in the [Mautic Conference Europe folder](https://www.canva.com/folder/FAFRkr_QhRk).

**Comment by DorcasOpatola** [comment]
Hi @RCheesley, could you assign this task to me?

**Comment by RCheesley** [comment]
Closing as completed by #39 thanks @DorcasOpatola 🚀

**Comment by DorcasOpatola** [comment]
Thank you @RCheesley !
It was a pleasure working on this issue with the team!😊
