### ISSUE TITLE
[Marketing] Write a feature about Hacktoberfest for the newsletter

### ISSUE THREAD

**Issue by RCheesley** [mautic/hacktoberfest-no-code#70]
This month we would like to feature Hacktoberfest in the newsletter. The monthly newsletter goes out on the first of the month.

This will need some content, some design and a bit of marketer magic to make it interesting and insightful.

Let us know if you want to work on this
Please write the content in this doc: https://docs.google.com/document/d/13zbB9POrYOjb6XsOewy3HH0LVeD0P_U77r1y4wifxmk/edit?usp=sharing

Please ask in #t-marketing if you're stuck.

**Comment by Brijeshthummar02** [comment]
@RCheesley do i have to add any file for this in repo or word text?

**Comment by RCheesley** [comment]
Hi @Brijeshthummar02 the content would need to be written in the Google Doc shared above. Once it's done and the marketing team approves it, then you would need to edit the 2024 file in the mautic/hacktoberfest-no-code repo to have your contribution count in Hacktoberfest.

**Comment by RCheesley** [comment]
I should also add that this content should be about the **experience** of hacktoberfest, not telling people to join. By 1 November the event is finished - so we should write a wrap up about the event.

For example, we could feature the number of contributions that were made, some comments from participants and mentors, team leads etc. You can use a placeholder to fill the actual numbers when we get closer to the end of the month.

If you like it could be in the format of a blog post, which we summarise into a section of the newsletter. 

Here's the last newsletter for inspiration: https://m.mautic.org/email/download/preview/231

**Comment by Brijeshthummar02** [comment]
@RCheesley where do i have to submit the Google doc.

**Comment by RCheesley** [comment]
@Brijeshthummar02 please could you ping us on Slack in #wg-mautic-newsletter and we can review it there. Thanks!

**Comment by RCheesley** [comment]
Closing this issue as we haven't had feedback and the newsletter has been published already.
